Server:
  Host: 0.0.0.0
  Port: 8000
  SessionTTL: 86400
  InsecureSkipVerify: true
Redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
ElasticSearch:
  Url: http://127.0.0.1:9200
  Username: ""
  Password: ""
Audit:
  LoginAuditIndex: gwebssh-login
  RecordAuditIndex: gwebssh-record
S3:
  Endpoint: 127.0.0.1:9000
  AccessKeyID: L1JigY9oU7lr9GyCQv14
  SecretAccessKey: 6DoFFEy7t2iuSguyMB80sozKBGjbDGIvT8Tn6HWK
  UseSSL: false
  Bucket: gwebssh

Guacd:
  Host: guacd
  Port: 4822
