Server:
  Ip: 0.0.0.0
  Port: 8080
Redis:
  Addr: 127.0.0.1:6379
  PassWord: ""
  DB: 0
ElasticSearch:
  Url: http://127.0.0.1:9200
  Username: ""
  Password: ""
Audit:
  LoginAuditIndex: webssh-login
  RecordAuditIndex: webssh-record
As3:
  EndPoint: 127.0.0.1:9000
  AccessKeyID: ""
  SecretAccessKey: ""
  UseSSL: true
  Bucket: webssh